### ISSUE TITLE
Two issues

### ISSUE THREAD

**Issue by THEDONKLER** [PranavBobbySekhar/FruitCollectGame#1]
### also some bugs related to json file handling it is automatically showing error and closing file.
ex - 
Traceback (most recent call last):
  File "C:\Users\daryl\OneDrive\Desktop\friute\main.py", line 138, in <module>
    data = json.load(read_file)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

thank. Hope am help

**Comment by PranavBobbySekhar** [comment]
To make the basket move slower, change the basket_speed variable on line 114 and 119 to the speed you want (make sure to leave the '-' sign as it is)

And for the json error, it's working well for me (even after download the code from here and running it). Please try running it again or try downloading the zip file once again.

**Comment by THEDONKLER** [comment]
> To make the basket move slower, change the basket_speed variable on line 114 and 119 to the speed you want (make sure to leave the '-' sign as it is)
> 
> And for the json error, it's working well for me (even after download the code from here and running it). Please try running it again or try downloading the zip file once again.

thank will try
